[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "coinbase-analyzer"
version = "1.0.0"
description = "Conbase feed analyzer CLI app for Kahoot!"
readme = "README.md"
requires-python = ">=3.11"
package-dir = {"" = "src"}
